export const LANG = {
    "": "Auto Detect",
    af: "Afrikaans",
    ar: "Arabic",
    bg: "Bulgarian",
    ca: "Catalan",
    yue: "Cantonese",
    "zh-Hans": "Chinese Simplified",
    "zh-Hant": "Chinese Traditional",
    hr: "Croatian",
    cs: "Czech",
    da: "Danish",
    nl: "Dutch",
    en: "English",
    et: "Estonian",
    tl: "Filipino",
    fi: "Finnish",
    fr: "French",
    de: "German",
    el: "Greek",
    iw: "Hebrew",
    hi: "Hindi",
    hu: "Hungarian",
    is: "Icelandic",
    it: "Italian",
    ja: "Japanese",
    ko: "Korean",
    lv: "Latvian",
    lt: "Lithuanian",
    ms: "Malay",
    mt: "Maltese",
    no: "Norwegian",
    fa: "Persian",
    pl: "Polish",
    pt: "Portuguese",
    ro: "Romanian",
    ru: "Russian",
    "sr-Latn": "Serbian",
    sk: "Slovak",
    sl: "Slovenian",
    es: "Spanish",
    sw: "Swahili",
    sv: "Swedish",
    th: "Thai",
    tr: "Turkish",
    uk: "Ukrainian",
    vi: "Vietnamese",
    cy: "Welsh"
};